//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/00 Main/00 Project Config/Input System/HIDInputComputer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HIDInputComputer: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HIDInputComputer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HIDInputComputer"",
    ""maps"": [
        {
            ""name"": ""Pilot"",
            ""id"": ""fa5954d5-eaa6-4cee-ac2b-17343a8d989d"",
            ""actions"": [
                {
                    ""name"": ""pCockpit.Mainclick"",
                    ""type"": ""Button"",
                    ""id"": ""52b884d1-ce6c-480b-8c5c-b99f245c567e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pCockpit.Directional"",
                    ""type"": ""Value"",
                    ""id"": ""81ae5b63-805f-4d5b-8714-11285a928d4b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""pCockpit.Secondaryclick"",
                    ""type"": ""Button"",
                    ""id"": ""6bcffde0-cb32-426c-b861-1e075b63a4c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""07ac28f7-d9e4-4f88-98c3-cc9ac457f6c1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pCockpit.Mainclick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccc5a3e8-df86-44ea-8aea-3c1edfa8cbb0"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pCockpit.Directional"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e93633ff-03bc-454f-b13a-01fdb527ab8f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pCockpit.Secondaryclick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Aircraftcontrols"",
            ""id"": ""0807af68-4b0b-4334-a655-7ea7861ec78c"",
            ""actions"": [
                {
                    ""name"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""type"": ""Value"",
                    ""id"": ""363749bd-7167-415c-b7c9-1d5289c68990"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""aAircraftcontrol.Airbrakecontrol.Override"",
                    ""type"": ""Value"",
                    ""id"": ""319e1d17-b0c3-4d55-aa26-8ef5fe925c28"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""aAircraftcontrol.Flapscontrol.Override"",
                    ""type"": ""Button"",
                    ""id"": ""5fa0c456-244b-4295-af53-180cf17e81c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""aAircraftcontrol.Gearcontrol.Override"",
                    ""type"": ""Button"",
                    ""id"": ""10163f29-f91a-440a-aba1-7d501c473841"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""515aa64b-5602-48b0-9548-56df27d4cf6a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Flapscontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5900b3ea-44b9-4e99-8d8c-cefb9095ebe0"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Gearcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Directionalcontrols.Override.Keyboard"",
                    ""id"": ""1a47dcda-cb2c-495c-8275-06a03e761230"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""955e2fa7-b075-4363-839d-acb039865b80"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bd327f5a-4d18-47ed-8e78-371910d781df"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1345a176-6999-409c-9b4f-f7a92436e028"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3d9f7325-aae4-49ab-bca5-3f877da311ec"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""21c1402c-cf81-4955-b98a-1ab14d71655d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""20931a04-1ea4-4e3c-9198-d83a7fc8747a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Directionalcontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""69fa7d1c-46e0-4fbe-a5be-212112cc2717"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aAircraftcontrol.Airbrakecontrol.Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debugcontrols"",
            ""id"": ""a4a0ba91-d68e-48ce-ba3f-4ee1e33c7d70"",
            ""actions"": [
                {
                    ""name"": ""pDebug.Debugcontrols.Togglecursor"",
                    ""type"": ""Button"",
                    ""id"": ""251aa365-dc28-4c1a-8704-c5efb58aab43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pDebug.Debugcontrols.Cursorleftclick"",
                    ""type"": ""Button"",
                    ""id"": ""0c71a814-dd11-409c-8443-35619c519bea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pDebug.Debugcontrols.CloseDebugWindow"",
                    ""type"": ""Button"",
                    ""id"": ""dbc4617c-a8a5-4ecd-a4b4-9acca277a3ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2384e315-b02f-48dc-88fd-36e63253cf0c"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pDebug.Debugcontrols.Togglecursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4c08e26-b6ed-488b-a0b7-1a65bda55326"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pDebug.Debugcontrols.Cursorleftclick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5354c0-eb46-4738-8f04-e8ec26bd9e85"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pDebug.Debugcontrols.CloseDebugWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Pilot
        m_Pilot = asset.FindActionMap("Pilot", throwIfNotFound: true);
        m_Pilot_pCockpitMainclick = m_Pilot.FindAction("pCockpit.Mainclick", throwIfNotFound: true);
        m_Pilot_pCockpitDirectional = m_Pilot.FindAction("pCockpit.Directional", throwIfNotFound: true);
        m_Pilot_pCockpitSecondaryclick = m_Pilot.FindAction("pCockpit.Secondaryclick", throwIfNotFound: true);
        // Aircraftcontrols
        m_Aircraftcontrols = asset.FindActionMap("Aircraftcontrols", throwIfNotFound: true);
        m_Aircraftcontrols_aAircraftcontrolDirectionalcontrolOverride = m_Aircraftcontrols.FindAction("aAircraftcontrol.Directionalcontrol.Override", throwIfNotFound: true);
        m_Aircraftcontrols_aAircraftcontrolAirbrakecontrolOverride = m_Aircraftcontrols.FindAction("aAircraftcontrol.Airbrakecontrol.Override", throwIfNotFound: true);
        m_Aircraftcontrols_aAircraftcontrolFlapscontrolOverride = m_Aircraftcontrols.FindAction("aAircraftcontrol.Flapscontrol.Override", throwIfNotFound: true);
        m_Aircraftcontrols_aAircraftcontrolGearcontrolOverride = m_Aircraftcontrols.FindAction("aAircraftcontrol.Gearcontrol.Override", throwIfNotFound: true);
        // Debugcontrols
        m_Debugcontrols = asset.FindActionMap("Debugcontrols", throwIfNotFound: true);
        m_Debugcontrols_pDebugDebugcontrolsTogglecursor = m_Debugcontrols.FindAction("pDebug.Debugcontrols.Togglecursor", throwIfNotFound: true);
        m_Debugcontrols_pDebugDebugcontrolsCursorleftclick = m_Debugcontrols.FindAction("pDebug.Debugcontrols.Cursorleftclick", throwIfNotFound: true);
        m_Debugcontrols_pDebugDebugcontrolsCloseDebugWindow = m_Debugcontrols.FindAction("pDebug.Debugcontrols.CloseDebugWindow", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Pilot
    private readonly InputActionMap m_Pilot;
    private List<IPilotActions> m_PilotActionsCallbackInterfaces = new List<IPilotActions>();
    private readonly InputAction m_Pilot_pCockpitMainclick;
    private readonly InputAction m_Pilot_pCockpitDirectional;
    private readonly InputAction m_Pilot_pCockpitSecondaryclick;
    public struct PilotActions
    {
        private @HIDInputComputer m_Wrapper;
        public PilotActions(@HIDInputComputer wrapper) { m_Wrapper = wrapper; }
        public InputAction @pCockpitMainclick => m_Wrapper.m_Pilot_pCockpitMainclick;
        public InputAction @pCockpitDirectional => m_Wrapper.m_Pilot_pCockpitDirectional;
        public InputAction @pCockpitSecondaryclick => m_Wrapper.m_Pilot_pCockpitSecondaryclick;
        public InputActionMap Get() { return m_Wrapper.m_Pilot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PilotActions set) { return set.Get(); }
        public void AddCallbacks(IPilotActions instance)
        {
            if (instance == null || m_Wrapper.m_PilotActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PilotActionsCallbackInterfaces.Add(instance);
            @pCockpitMainclick.started += instance.OnPCockpitMainclick;
            @pCockpitMainclick.performed += instance.OnPCockpitMainclick;
            @pCockpitMainclick.canceled += instance.OnPCockpitMainclick;
            @pCockpitDirectional.started += instance.OnPCockpitDirectional;
            @pCockpitDirectional.performed += instance.OnPCockpitDirectional;
            @pCockpitDirectional.canceled += instance.OnPCockpitDirectional;
            @pCockpitSecondaryclick.started += instance.OnPCockpitSecondaryclick;
            @pCockpitSecondaryclick.performed += instance.OnPCockpitSecondaryclick;
            @pCockpitSecondaryclick.canceled += instance.OnPCockpitSecondaryclick;
        }

        private void UnregisterCallbacks(IPilotActions instance)
        {
            @pCockpitMainclick.started -= instance.OnPCockpitMainclick;
            @pCockpitMainclick.performed -= instance.OnPCockpitMainclick;
            @pCockpitMainclick.canceled -= instance.OnPCockpitMainclick;
            @pCockpitDirectional.started -= instance.OnPCockpitDirectional;
            @pCockpitDirectional.performed -= instance.OnPCockpitDirectional;
            @pCockpitDirectional.canceled -= instance.OnPCockpitDirectional;
            @pCockpitSecondaryclick.started -= instance.OnPCockpitSecondaryclick;
            @pCockpitSecondaryclick.performed -= instance.OnPCockpitSecondaryclick;
            @pCockpitSecondaryclick.canceled -= instance.OnPCockpitSecondaryclick;
        }

        public void RemoveCallbacks(IPilotActions instance)
        {
            if (m_Wrapper.m_PilotActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPilotActions instance)
        {
            foreach (var item in m_Wrapper.m_PilotActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PilotActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PilotActions @Pilot => new PilotActions(this);

    // Aircraftcontrols
    private readonly InputActionMap m_Aircraftcontrols;
    private List<IAircraftcontrolsActions> m_AircraftcontrolsActionsCallbackInterfaces = new List<IAircraftcontrolsActions>();
    private readonly InputAction m_Aircraftcontrols_aAircraftcontrolDirectionalcontrolOverride;
    private readonly InputAction m_Aircraftcontrols_aAircraftcontrolAirbrakecontrolOverride;
    private readonly InputAction m_Aircraftcontrols_aAircraftcontrolFlapscontrolOverride;
    private readonly InputAction m_Aircraftcontrols_aAircraftcontrolGearcontrolOverride;
    public struct AircraftcontrolsActions
    {
        private @HIDInputComputer m_Wrapper;
        public AircraftcontrolsActions(@HIDInputComputer wrapper) { m_Wrapper = wrapper; }
        public InputAction @aAircraftcontrolDirectionalcontrolOverride => m_Wrapper.m_Aircraftcontrols_aAircraftcontrolDirectionalcontrolOverride;
        public InputAction @aAircraftcontrolAirbrakecontrolOverride => m_Wrapper.m_Aircraftcontrols_aAircraftcontrolAirbrakecontrolOverride;
        public InputAction @aAircraftcontrolFlapscontrolOverride => m_Wrapper.m_Aircraftcontrols_aAircraftcontrolFlapscontrolOverride;
        public InputAction @aAircraftcontrolGearcontrolOverride => m_Wrapper.m_Aircraftcontrols_aAircraftcontrolGearcontrolOverride;
        public InputActionMap Get() { return m_Wrapper.m_Aircraftcontrols; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AircraftcontrolsActions set) { return set.Get(); }
        public void AddCallbacks(IAircraftcontrolsActions instance)
        {
            if (instance == null || m_Wrapper.m_AircraftcontrolsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AircraftcontrolsActionsCallbackInterfaces.Add(instance);
            @aAircraftcontrolDirectionalcontrolOverride.started += instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolDirectionalcontrolOverride.performed += instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolDirectionalcontrolOverride.canceled += instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.started += instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.performed += instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.canceled += instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.started += instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.performed += instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.canceled += instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolGearcontrolOverride.started += instance.OnAAircraftcontrolGearcontrolOverride;
            @aAircraftcontrolGearcontrolOverride.performed += instance.OnAAircraftcontrolGearcontrolOverride;
            @aAircraftcontrolGearcontrolOverride.canceled += instance.OnAAircraftcontrolGearcontrolOverride;
        }

        private void UnregisterCallbacks(IAircraftcontrolsActions instance)
        {
            @aAircraftcontrolDirectionalcontrolOverride.started -= instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolDirectionalcontrolOverride.performed -= instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolDirectionalcontrolOverride.canceled -= instance.OnAAircraftcontrolDirectionalcontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.started -= instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.performed -= instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolAirbrakecontrolOverride.canceled -= instance.OnAAircraftcontrolAirbrakecontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.started -= instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.performed -= instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolFlapscontrolOverride.canceled -= instance.OnAAircraftcontrolFlapscontrolOverride;
            @aAircraftcontrolGearcontrolOverride.started -= instance.OnAAircraftcontrolGearcontrolOverride;
            @aAircraftcontrolGearcontrolOverride.performed -= instance.OnAAircraftcontrolGearcontrolOverride;
            @aAircraftcontrolGearcontrolOverride.canceled -= instance.OnAAircraftcontrolGearcontrolOverride;
        }

        public void RemoveCallbacks(IAircraftcontrolsActions instance)
        {
            if (m_Wrapper.m_AircraftcontrolsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAircraftcontrolsActions instance)
        {
            foreach (var item in m_Wrapper.m_AircraftcontrolsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AircraftcontrolsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AircraftcontrolsActions @Aircraftcontrols => new AircraftcontrolsActions(this);

    // Debugcontrols
    private readonly InputActionMap m_Debugcontrols;
    private List<IDebugcontrolsActions> m_DebugcontrolsActionsCallbackInterfaces = new List<IDebugcontrolsActions>();
    private readonly InputAction m_Debugcontrols_pDebugDebugcontrolsTogglecursor;
    private readonly InputAction m_Debugcontrols_pDebugDebugcontrolsCursorleftclick;
    private readonly InputAction m_Debugcontrols_pDebugDebugcontrolsCloseDebugWindow;
    public struct DebugcontrolsActions
    {
        private @HIDInputComputer m_Wrapper;
        public DebugcontrolsActions(@HIDInputComputer wrapper) { m_Wrapper = wrapper; }
        public InputAction @pDebugDebugcontrolsTogglecursor => m_Wrapper.m_Debugcontrols_pDebugDebugcontrolsTogglecursor;
        public InputAction @pDebugDebugcontrolsCursorleftclick => m_Wrapper.m_Debugcontrols_pDebugDebugcontrolsCursorleftclick;
        public InputAction @pDebugDebugcontrolsCloseDebugWindow => m_Wrapper.m_Debugcontrols_pDebugDebugcontrolsCloseDebugWindow;
        public InputActionMap Get() { return m_Wrapper.m_Debugcontrols; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugcontrolsActions set) { return set.Get(); }
        public void AddCallbacks(IDebugcontrolsActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugcontrolsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugcontrolsActionsCallbackInterfaces.Add(instance);
            @pDebugDebugcontrolsTogglecursor.started += instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsTogglecursor.performed += instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsTogglecursor.canceled += instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsCursorleftclick.started += instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCursorleftclick.performed += instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCursorleftclick.canceled += instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCloseDebugWindow.started += instance.OnPDebugDebugcontrolsCloseDebugWindow;
            @pDebugDebugcontrolsCloseDebugWindow.performed += instance.OnPDebugDebugcontrolsCloseDebugWindow;
            @pDebugDebugcontrolsCloseDebugWindow.canceled += instance.OnPDebugDebugcontrolsCloseDebugWindow;
        }

        private void UnregisterCallbacks(IDebugcontrolsActions instance)
        {
            @pDebugDebugcontrolsTogglecursor.started -= instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsTogglecursor.performed -= instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsTogglecursor.canceled -= instance.OnPDebugDebugcontrolsTogglecursor;
            @pDebugDebugcontrolsCursorleftclick.started -= instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCursorleftclick.performed -= instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCursorleftclick.canceled -= instance.OnPDebugDebugcontrolsCursorleftclick;
            @pDebugDebugcontrolsCloseDebugWindow.started -= instance.OnPDebugDebugcontrolsCloseDebugWindow;
            @pDebugDebugcontrolsCloseDebugWindow.performed -= instance.OnPDebugDebugcontrolsCloseDebugWindow;
            @pDebugDebugcontrolsCloseDebugWindow.canceled -= instance.OnPDebugDebugcontrolsCloseDebugWindow;
        }

        public void RemoveCallbacks(IDebugcontrolsActions instance)
        {
            if (m_Wrapper.m_DebugcontrolsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugcontrolsActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugcontrolsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugcontrolsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugcontrolsActions @Debugcontrols => new DebugcontrolsActions(this);
    public interface IPilotActions
    {
        void OnPCockpitMainclick(InputAction.CallbackContext context);
        void OnPCockpitDirectional(InputAction.CallbackContext context);
        void OnPCockpitSecondaryclick(InputAction.CallbackContext context);
    }
    public interface IAircraftcontrolsActions
    {
        void OnAAircraftcontrolDirectionalcontrolOverride(InputAction.CallbackContext context);
        void OnAAircraftcontrolAirbrakecontrolOverride(InputAction.CallbackContext context);
        void OnAAircraftcontrolFlapscontrolOverride(InputAction.CallbackContext context);
        void OnAAircraftcontrolGearcontrolOverride(InputAction.CallbackContext context);
    }
    public interface IDebugcontrolsActions
    {
        void OnPDebugDebugcontrolsTogglecursor(InputAction.CallbackContext context);
        void OnPDebugDebugcontrolsCursorleftclick(InputAction.CallbackContext context);
        void OnPDebugDebugcontrolsCloseDebugWindow(InputAction.CallbackContext context);
    }
}
